/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint8_t currentTask = 0; // 0 means task1
uint32_t g_tickCount = 0;

typedef struct {
	uint32_t pspValue;
	uint32_t blockCount;
	uint8_t currentState;
	void (*taskHandler)();
} TCB_t;

TCB_t userTasks[MAX_TASKS];

void enable_processor_faults();
__attribute__((naked)) void switch_sp_to_psp();
void task_delay(uint32_t tickCount);
__attribute__((naked)) void init_scheduler_stack(uint32_t schedStackStart);
void init_tasks_stack();
void init_systick_timer(uint32_t tickHz);

void idle_task();
void task1_handler();
void task2_handler();
void task3_handler();
void task4_handler();

int main(void)
{
	enable_processor_faults();

	init_scheduler_stack(SCHED_STACK_START);

	init_tasks_stack();

	led_init_all();

	init_systick_timer(TICK_HZ);

	switch_sp_to_psp();

	task1_handler();

    /* Loop forever */
	for(;;);
}

void enable_processor_faults()
{
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;

	*pSHCSR |= (1 << 16); // Enable memmanage fault
	*pSHCSR |= (1 << 17); // Enable bus fault
	*pSHCSR |= (1 << 18); // Enable usage fault
}

uint32_t get_psp_value()
{
	return userTasks[currentTask].pspValue;
}

void save_psp_value(uint32_t current_psp_value)
{
	userTasks[currentTask].pspValue = current_psp_value;
}

void update_next_task()
{
	int state = TASK_BLOCKED_STATE;

	for (int i = 0; i < MAX_TASKS; i++)
	{
		currentTask++;
		currentTask %= MAX_TASKS;
		state = userTasks[currentTask].currentState;
		if ((state == TASK_READY_STATE) && (currentTask != 0))
			break;
	}

	if (state != TASK_READY_STATE)
		currentTask = 0;
}

__attribute__((naked)) void switch_sp_to_psp()
{
	// Initialize PSP with task1 stack start
	__asm volatile("PUSH {LR};"); // Save LR which will return this function to the caller
	__asm volatile("BL get_psp_value;"); // Get PSP of current task
	__asm volatile("MSR PSP, R0;"); // Save the current task's PSP value into the PSP register
	__asm volatile("POP {LR};"); // Load LR back from the stack

	// Change SP to PSP using control register
	__asm volatile("MOV R0, #0x02;");
	__asm volatile("MSR CONTROL, R0;");

	// Return to the caller
	__asm volatile("BX LR;");
}

void idle_task()
{
	while(1);
}

void task1_handler()
{
	while(1)
	{
		led_on(LED_GREEN);
		task_delay(1000);
		led_off(LED_GREEN);
		task_delay(1000);
	}
}

void task2_handler()
{
	while(1)
	{
		led_on(LED_ORANGE);
		task_delay(500);
		led_off(LED_ORANGE);
		task_delay(500);
	}
}

void task3_handler()
{
	while(1)
	{
		led_on(LED_BLUE);
		task_delay(250);
		led_off(LED_BLUE);
		task_delay(250);
	}
}

void task4_handler()
{
	while(1)
	{
		led_on(LED_RED);
		task_delay(125);
		led_off(LED_RED);
		task_delay(125);
	}
}

void schedule()
{
	// Pend the PendSV exception
	uint32_t* pICSR = (uint32_t*)0xE000ED04;
	*pICSR |= (1 << 28);
}

#define INTERRUPT_DISABLE() do { __asm volatile("MOV R0, #0x01;"); __asm volatile("MSR PRIMASK, R0;"); } while(0)

#define INTERRUPT_ENABLE() do { __asm volatile("MOV R0, #0x00;"); __asm volatile("MSR PRIMASK, R0;"); } while(0)

void task_delay(uint32_t tickCount)
{
	INTERRUPT_DISABLE();

	// Delay only if current task is not 0 i.e. idle task
	if (currentTask)
	{
		userTasks[currentTask].blockCount = g_tickCount + tickCount;
		userTasks[currentTask].currentState = TASK_BLOCKED_STATE;
		schedule();
	}

	INTERRUPT_ENABLE();
}

__attribute__((naked)) void init_scheduler_stack(uint32_t schedStackStart)
{
	__asm volatile("MSR MSP, %0;":: "r"(schedStackStart) :);
	__asm volatile("BX LR;");
}

void init_tasks_stack()
{
	userTasks[0].currentState = TASK_READY_STATE;
	userTasks[1].currentState = TASK_READY_STATE;
	userTasks[2].currentState = TASK_READY_STATE;
	userTasks[3].currentState = TASK_READY_STATE;
	userTasks[4].currentState = TASK_READY_STATE;

	userTasks[0].pspValue = IDLE_STACK_START;
	userTasks[1].pspValue = T1_STACK_START;
	userTasks[2].pspValue = T2_STACK_START;
	userTasks[3].pspValue = T3_STACK_START;
	userTasks[4].pspValue = T4_STACK_START;

	userTasks[0].taskHandler = idle_task;
	userTasks[1].taskHandler = task1_handler;
	userTasks[2].taskHandler = task2_handler;
	userTasks[3].taskHandler = task3_handler;
	userTasks[4].taskHandler = task4_handler;

	uint32_t* pPSP;

	for (int i = 0; i < MAX_TASKS; i++)
	{
		pPSP = (uint32_t*)userTasks[i].pspValue;

		// Decrementing stack pointer first since the stack is full descending
		// Initialize xPSR
		pPSP--;
		*pPSP = DUMMY_XPSR; // 0x01000000

		// Initialize PC
		pPSP--;
		*pPSP = (uint32_t)userTasks[i].taskHandler;

		// Initialize LR
		pPSP--;
		*pPSP = 0xFFFFFFFD; // Value of EXEC_RETURN

		// Initialize general registers
		for (int j = 0; j < 13; j++)
		{
			pPSP--;
			*pPSP = 0;
		}

		// Update current task PSP
		userTasks[i].pspValue = (uint32_t)pPSP;
	}
}

void init_systick_timer(uint32_t tickHz)
{
	uint32_t *pSRVR = (uint32_t*)0xE000E014;
	uint32_t *pSCSR = (uint32_t*)0xE000E010;
	uint32_t countValue = SYSTICK_TIM_CLK / tickHz - 1;

	// Clear existing SRVR value
	*pSRVR &= ~(0x00FFFFFF);

	// Load the reload value into SRVR
	*pSRVR |= countValue;

	// Configure SCSR
	*pSCSR |= 7;
}

void HardFault_Handler()
{
	printf("Exception: HardFault\n");
	while(1);
}

void MemManage_Handler()
{
	printf("Exception: MemManageFault\n");
	while(1);
}

void BusFault_Handler()
{
	printf("Exception: BusFault\n");
	while(1);
}

void UsageFault_Handler()
{
	printf("Exception: UsageFault\n");
	while(1);
}

__attribute__((naked)) void PendSV_Handler()
{
	// Save the context of current task

		// Get the current task's PSP
		__asm volatile("MRS R0, PSP;");

		// Using the PSP, save SF2(R4 - R11)
		__asm volatile("STMDB R0!, {R4-R11};");

		// Preserve LR to be able to properly exit current interrupt handler
		__asm volatile("PUSH {LR};");

		// Save the current value of PSP
		__asm volatile("BL save_psp_value;"); // R0 already has the current PSP value

		// Retrieve the context of next task

		// Decide next task to run
		__asm volatile("BL update_next_task;");

		// Get its past PSP value
		__asm volatile("BL get_psp_value;");

		// Using retrieved PSP, retrieve SF2(R4 - R11)
		__asm volatile("LDMIA R0!, {R4-R11};");

		// Update PSP and exit
		__asm volatile("MSR PSP, R0;");

		// Load back LR to be able to properly exit current interrupt handler
		__asm volatile("POP {LR};");

		// Exit current interrupt handler
		__asm volatile("BX LR;");
}

void update_global_tick_count()
{
	g_tickCount++;
}

void unblock_tasks()
{
	for (int i = 1; i < MAX_TASKS; i++)
	{
		if (userTasks[i].currentState != TASK_READY_STATE)
		{
			if (userTasks[i].blockCount == g_tickCount)
			{
				userTasks[i].currentState = TASK_READY_STATE;
			}
		}
	}
}

void SysTick_Handler()
{
	uint32_t* pICSR = (uint32_t*)0xE000ED04;

	update_global_tick_count();
	unblock_tasks();

	// Pend the PendSV exception
	*pICSR |= (1 << 28);
}
